modLoader = "javafml"
loaderVersion = "[43,)"
license = "GPLv3"
[[mods]]
modId = "tameablezombieskeletonhorse"
version = "1.20.1-1.1.0"
displayName = "Tameable Zombie Horse 'n Skeleton Horse"
authors = [
    "Rinko1231"
]
description = "Make Zombie Horse and Skeleton Horse Tameable and Armor-Capable! Dread Horse from Ice'n Fire is also supported. "
[[mixins]]
config = "tameablezombieskeletonhorse.mixins.json"